---
version: "3.1"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config:/config
      - ./gallery:/gallery
    ports:
      - 8080:80
      - 8443:443
    networks:
      - public
      - default
    restart: unless-stopped

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: piwigo
      MARIADB_USER: piwigo
      MARIADB_PASSWORD: Asdfqwer1234
      MARIADB_ROOT_PASSWORD: Qwerasdf1234
    networks:
      - default
    volumes:
      - ./mariadb:/var/lib/mysql

# a little admin gui for mariadb / mysql
#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8081:8080
#    networks:
#      - public
#      - default

# make sure the public network uses the bridge
# to be available on localhost on windows as well
networks:
  default:
  public:
    driver: bridge